# Generated by Django 5.1.2 on 2024-10-22 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('15', '15 minutes'), ('30', '30 minutes'), ('45', '45 minutes'), ('60', '60 minutes'), ('75', '75 minutes'), ('90', '90 minutes')], max_length=3)),
                ('target_area', models.CharField(choices=[('Core/Abs', 'Core/Abs'), ('Legs', 'Legs'), ('Arms', 'Arms'), ('Full Body', 'Full Body'), ('Chest', 'Chest'), ('Back', 'Back')], max_length=50)),
                ('equipment', models.CharField(choices=[('Dumbbells', 'Dumbbells'), ('Barbell', 'Barbell'), ('Bench', 'Bench'), ('Squat Rack', 'Squat Rack'), ('Cables', 'Cables'), ('Bodyweight', 'Bodyweight')], max_length=50)),
                ('custom_target', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
