# Generated by Django 5.1.2 on 2024-10-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="sections",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
